version: '3.9'

services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"

  mqtt:
    build: ./mqtt
    container_name: mqtt
    restart: always
    ports:
      - "1883:1883"
      - "9001:9001"

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - MONGO_URL=mongodb://mongo:27017/vaja6
    depends_on:
      - mongo

  api:
    build: ./API
    container_name: api
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mqtt
      - backend

  frontend_web:
    build: ./frontend_web
    container_name: frontend_web
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
      - api

  frontend_mobile:
    build: ./frontweb_mobile
    container_name: frontweb_mobile
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - backend
      - api

volumes:
  mongo-data:
