version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:2.0
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./dump:/dump 

  backend:
    build: ./backend
    container_name: backend
    network_mode: host
    depends_on:
      - mongo

  frontend-web:
    build: ./frontend_web
    container_name: frontend-web
    ports:
      - "3000:3000"
    depends_on:
      - backend

  flask-api:
    build: ./API
    container_name: flask-face-api
    ports:
      - "5000:5000"
    depends_on:
      - mosquitto

  frontweb-mobile:
    build: ./frontweb_mobile
    container_name: frontweb-mobile
    network_mode: "host"
    stdin_open: true
    tty: true
    depends_on:
      - backend
    

volumes:
  mongo-data:

