name: Backend CI

on: [push, pull_request]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongo --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install
      - name: Install MongoDB Database Tools
        run: |
          wget https://fastdl.mongodb.org/tools/db/mongodb-database-tools-ubuntu2004-x86_64-100.9.4.tgz
          tar -xvzf mongodb-database-tools-*-100.9.4.tgz
          sudo cp mongodb-database-tools-*/bin/* /usr/local/bin/

      - name: Restore MongoDB dump
        run: |
          mongorestore --host 127.0.0.1 --port 27017 --db vaja6 dump/vaja6

      - name: Run tests
        env:
          MONGO_URL: mongodb://127.0.0.1/vaja6
        run: |
          cd backend
          npm test
